# Generated by Django 5.0.6 on 2024-06-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dog_territory_battle_game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="current_turn",
            new_name="current_turn_id",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="winner",
            new_name="winner_id",
        ),
    ]
