# Generated by Django 5.0.6 on 2024-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dog_territory_battle_game", "0003_rename_current_turn_id_game_current_turn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="is_in_hand",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="x_position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="y_position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
