name: E2E Test

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # バックエンドのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Migrate database
        run: |
          python manage.py migrate

      - name: Start backend server
        run: |
          python manage.py runserver 0.0.0.0:8000 &
        shell: bash

      - name: Wait for backend to start
        run: sleep 10

      # フロントエンドのセットアップ
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install frontend dependencies
        working-directory: ./dog-territory-battle
        run: |
          npm install

      - name: Start frontend server
        working-directory: ./dog-territory-battle
        run: |
          npm start &
        shell: bash

      - name: Wait for frontend to start
        run: sleep 10

      # E2E テストの実行
      - name: Run Cypress tests
        working-directory: ./dog-territory-battle
        run: |
          npx cypress run